services:
  qr:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/var/www/app/qr
      - ./static:/var/www/app/qr/static
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: python app.py

  web:
    image: nginx
    container_name: nginx_html
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always
